apiVersion: v1
kind: Pod
metadata:
  name: s3-test-pod
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: s3-volume
  volumes:
    - name: s3-volume
      persistentVolumeClaim:
        claimName: s3-pvc
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000
