apiVersion: batch/v1
kind: CronJob
metadata:
  name: pingpong-secret
  labels:
    app: pingpong-secret
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: pingpong-secret
        spec:
          containers:
          - name: pingpong-secret
            image: ubuntu:23.10
            env:
            - name: ENV_TEXT
              value: hi
            - name: SECRET_TEXT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: PASSWORD
            command:
              - "sh"
              - "-c"
              - |
                echo [`date`] $ENV_TEXT $SECRET_TEXT!
                sleep 10
                echo [`date`] $ENV_TEXT $SECRET_TEXT!
                sleep 10
                echo [`date`] $ENV_TEXT $SECRET_TEXT!
          restartPolicy: OnFailure
