apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cover-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/searer/eks-study-helm.git
    targetRevision: main
    path: apps/cover
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
